args: !!python/object/new:easydict.EasyDict
  dictitems:
    batch_size: 1
    epoch: 200
    img_size: 128
    init_lr: 0.0001
    seed: 41
    weight_decay: 0.05
  state:
    batch_size: 1
    epoch: 200
    img_size: 128
    init_lr: 0.0001
    seed: 41
    weight_decay: 0.05
