args: !!python/object/new:easydict.EasyDict
  dictitems:
    aug_Lv: 0
    augmentation_cfg: &id001 !!python/object:easydict.EasyDict {}
    batch_size: 1
    epoch: 500
    img_size: &id002
    - 128
    - 256
    init_lr: 1.0e-05
    intensity_cfg: &id003 !!python/object/new:easydict.EasyDict
      dictitems:
        Xray_max: 255
        Xray_min: 0.0
        clip: true
        znorm_mean: 0.4309305409308814
        znorm_std: 0.25163892359754375
      state:
        Xray_max: 255
        Xray_min: 0.0
        clip: true
        znorm_mean: 0.4309305409308814
        znorm_std: 0.25163892359754375
    is_randAug: false
    lr_dec_rate: 0.01
    seed: 411
    server: KTL
    weight_decay: 0.0
  state:
    aug_Lv: 0
    augmentation_cfg: *id001
    batch_size: 1
    epoch: 500
    img_size: *id002
    init_lr: 1.0e-05
    intensity_cfg: *id003
    is_randAug: false
    lr_dec_rate: 0.01
    seed: 411
    server: KTL
    weight_decay: 0.0
