args: !!python/object/new:easydict.EasyDict
  dictitems:
    aug_Lv: 1
    augmentation_cfg: &id004 !!python/object/new:easydict.EasyDict
      dictitems:
        elastic_magnitude_range: &id001
        - 100
        - 400
        elastic_prob: 0.2
        elastic_sigma_range: &id002
        - 5
        - 13
        flip_prob: 0.5
        gamma_prob: 0.2
        gamma_range: &id003
        - 0.7
        - 1.5
        rotation_degree: 0.2617993877991494
        rotation_prob: 0.2
        scaling_fator: 0.25
        scaling_prob: 0.2
      state:
        elastic_magnitude_range: *id001
        elastic_prob: 0.2
        elastic_sigma_range: *id002
        flip_prob: 0.5
        gamma_prob: 0.2
        gamma_range: *id003
        rotation_degree: 0.2617993877991494
        rotation_prob: 0.2
        scaling_fator: 0.25
        scaling_prob: 0.2
    batch_size: 16
    epoch: 500
    img_size: &id005
    - 128
    - 256
    init_lr: 0.0001
    intensity_cfg: &id006 !!python/object/new:easydict.EasyDict
      dictitems:
        Xray_max: 255
        Xray_min: 0.0
        clip: true
        znorm_mean: 0.4690341824996129
        znorm_std: 0.30681989313646496
      state:
        Xray_max: 255
        Xray_min: 0.0
        clip: true
        znorm_mean: 0.4690341824996129
        znorm_std: 0.30681989313646496
    is_randAug: false
    lr_dec_rate: 0.01
    seed: 411
    server: KTL
    weight_decay: 0.0
  state:
    aug_Lv: 1
    augmentation_cfg: *id004
    batch_size: 16
    epoch: 500
    img_size: *id005
    init_lr: 0.0001
    intensity_cfg: *id006
    is_randAug: false
    lr_dec_rate: 0.01
    seed: 411
    server: KTL
    weight_decay: 0.0
